#!/usr/bin/env bash
# Auto-generated by scripts/fix_naming.py
# Renames experiment directories to match current naming convention.
set -euo pipefail

# bit_keep_conv1_kd_s123 -> bit_kd_keep_conv1_s123
mv "results/raw_kd/cifar100/resnet18/bit_keep_conv1_kd_s123" "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s123"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s123/config.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s123/bit_kd_keep_conv1_s123/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s123/config.json"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s123/results.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s123/bit_kd_keep_conv1_s123/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s123/results.json"

# bit_keep_conv1_kd_s42 -> bit_kd_keep_conv1_s42
mv "results/raw_kd/cifar100/resnet18/bit_keep_conv1_kd_s42" "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s42"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s42/config.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s42/bit_kd_keep_conv1_s42/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s42/config.json"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s42/results.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s42/bit_kd_keep_conv1_s42/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s42/results.json"

# bit_keep_conv1_kd_s456 -> bit_kd_keep_conv1_s456
mv "results/raw_kd/cifar100/resnet18/bit_keep_conv1_kd_s456" "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s456"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s456/config.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s456/bit_kd_keep_conv1_s456/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s456/config.json"
[ -f "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s456/results.json" ] && sed -i'' -e 's/bit_keep_conv1_kd_s456/bit_kd_keep_conv1_s456/g' "results/raw_kd/cifar100/resnet18/bit_kd_keep_conv1_s456/results.json"

